# Generated by Django 3.0.7 on 2020-06-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inwarddate', models.DateField(auto_now_add=True)),
                ('billno', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'materialinward',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('specification', models.CharField(max_length=255)),
                ('minStock', models.FloatField()),
                ('reOrderPoint', models.FloatField()),
                ('minOrderQty', models.FloatField()),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=255)),
                ('vend_address', models.TextField()),
                ('gstno', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'vendor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poqty', models.FloatField()),
                ('rate', models.FloatField()),
                ('cancleqty', models.FloatField()),
                ('pending_qty', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            options={
                'db_table': 'purchaseorder_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pono', models.CharField(max_length=100)),
                ('podate', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Vendor')),
            ],
            options={
                'db_table': 'purchaseorder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedate', models.DateField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Vendor')),
            ],
            options={
                'db_table': 'materialissue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaterialInward_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inwardqty', models.FloatField()),
                ('issuedqty', models.FloatField()),
                ('materialinward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.MaterialInward')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.PurchaseOrder_Detail')),
            ],
            options={
                'db_table': 'materialinward_detail',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='materialinward',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Vendor'),
        ),
    ]
