# Generated by Django 3.0.7 on 2020-06-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinward',
            name='inwarddate',
            field=models.DateField(),
        ),
    ]
