# Generated by Django 3.0.7 on 2020-06-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200607_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder_detail',
            name='purchaseorder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.PurchaseOrder'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='podate',
            field=models.DateField(),
        ),
    ]
