# Generated by Django 3.0.7 on 2020-06-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200610_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialinward_detail',
            name='product',
        ),
        migrations.AddField(
            model_name='materialinward_detail',
            name='purchasedetail',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.PurchaseOrder_Detail'),
        ),
        migrations.AlterField(
            model_name='purchaseorder_detail',
            name='cancleqty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder_detail',
            name='pending_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder_detail',
            name='purchaseorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.PurchaseOrder'),
        ),
    ]
